---
ansible_python_interpreter: /usr/bin/python3

ldap_version: 3
ldap_home_umask: "0022"
ldap_tls_reqcert: never
ldap_uri: ldap://172.16.203.20
ldap_base: ou=Users,dc=lab,dc=loxda,dc=net
ldap_scope: sub
ldap_bind_timelimit: 50
ldap_search_timelimit: 50
ldap_binddn: cn=bind,dc=lab,dc=loxda,dc=net
ldap_bindpw: papillon
ldap_pagesize: 1000
ldap_referrals: 'yes'
ldap_idle_timelimit: 300
ldap_filters: |
  filter passwd (|(objectClass=posixAccount)(objectClass=inetOrgPerson))
  filter shadow (|(objectClass=posixAccount)(objectClass=inetOrgPerson))
  filter group  (|(objectClass=posixGroup)(Objectclass=posixAccount))
ldap_nslcd_extra_params: |
  nss_initgroups_ignoreusers root
  pam_authz_search (&(objectClass=posixAccount)(uid=$username))
  pam_password_prohibit_message "Change your password on Self Service Portal. thx bro."

#emulate pam_attr_host and negative behavior
#pam_authz_search (&(objectClass=posixAccount)(uid=$username)(|(host=$hostname)(host=$fqdn)(&(host=\\*)(!(|(host=!$hostname)(host=!$fqdn))))))

tmux_packages: tmux
tmux_packages_state: present
tmux_plugin_dir: .tmux/plugins
tmux_conf_template: tmux.conf
tmux_conf_dir: .tmux
tmux_conf_file: .tmux.conf
tmux_conf_force: false
tmux_plugins:
  - { name: "tpm", repo: "https://github.com/tbasset/tpm.git", version: "v3.0.0" }

powerline_default_top_theme: powerline

