---
- hosts: lab
  gather_facts: true

  pre_tasks:

    - name: test
      debug: 
        msg: 
          - "{{ inventory_hostname | d('') }}"
          # - "{{ hostvars[inventory_hostname] | d('') }}"
          - "groups={{ inventory_hostname[groups] | d('') }}"
          - "env_home={{ env_home | d('') }}"
          - "group_vars_folder={{ group_vars_folder | d('') }}"
          - "group_vars_inventory_folder={{ group_vars_inventory_folder | d('') }}"
          - "src={{ vlan_src | d('') }}"
          - "vlan_num=={{ vlan_num | d('') }}"
          - "vlan_name={{ vlan_name | d('') }}"
          - "vlan_ipv4_sub={{ vlan_ipv4_sub | d('') }}"
          - "vlan_ipv4_gw={{ vlan_ipv4_gw | d('') }}"

  roles:
    - role: ansible-role-grub
      tags: 
        - grub
        - never
#    - ansible-role-hosts
#    - ansible-role-resolv
    - role: ansible-role-interfaces
#    - ansible-role-firewall
    - role: ansible-role-ca-certificates
    - role: ansible-role-ldap
    - role: ansible-role-tmux
    - role: ansible-role-powerline
