---
- hosts: lab
  gather_facts: true

  pre_tasks:

    - name: test
      debug: 
        msg: 
          - "host={{ inventory_hostname | d('') }}"
          # - "{{ hostvars[inventory_hostname] | d('') }}"
          - "groups={{ inventory_hostname[groups] | d('') }}"
          - "env_home={{ env_home | d('') }}"
          - "group_vars_folder={{ group_vars_folder | d('') }}"
          - "group_vars_inventory_folder={{ group_vars_inventory_folder | d('') }}"
          - "src={{ vlan_src | d('') }}"
          - "vlan_num=={{ vlan_num | d('') }}"
          - "vlan_name={{ vlan_name | d('') }}"
          - "vlan_ipv4_sub={{ vlan_ipv4_sub | d('') }}"
          - "vlan_ipv4_gw={{ vlan_ipv4_gw | d('') }}"
      tags: 
        - always

  roles:

    - role: ansible-role-grub
      tags: 
        - grub
        - never
#    - role: ansible-role-hosts
#      tags: 
#        - hosts
#        - never

#    - role: ansible-role-resolv
#      tags: 
#        - resolv
#        - never
    - role: ansible-role-interfaces
      tags: 
        - network
        - never
#    - ansible-role-firewall
    - role: ansible-role-ca-certificates
      tags: 
        - cacerts
        - never
    - role: ansible-role-ldap
      tags: 
        - ldap
        - never
    - role: ansible-role-tmux
      tags: 
        - tmux
        - never
    - role: ansible-role-powerline
      tags: 
        - powerline
        - never

  post_tasks:

    - name: test
      debug: 
        msg: 
          - "finish."
      tags: 
        - always
