---
- hosts: localhost
  gather_facts: true
  roles:
    - role: ansible-role-grub
      tags: 
        - grub
        - never
#    - ansible-role-hosts
#    - ansible-role-resolv
    - ansible-role-interfaces
#    - ansible-role-firewall
    - ansible-role-ca-certificates
    - ansible-role-ldap
    - ansible-role-tmux
    - ansible-role-powerline
