---
- hosts: localhost
  gather_facts: true
  roles:
    - role: ansible-role-grub
      tags: 
        - grub
        - never
    - ansible-role-interfaces
    - ansible-role-ca-certificates
    - ansible-role-ldap
    - ansible-role-tmux
    - ansible-role-powerline
    - ansible-role-interfaces
