---
- hosts: localhost
  gather_facts: false

  tasks:

    - debug: 
        msg: 
          - "src={{vlan_src}}"
          - "vlan_num=={{vlan_num}}"
          - "vlan_name={{vlan_name}}"
          - "vlan_ipv4_sub={{vlan_ipv4_sub}}"
          - "vlan_ipv4_gw={{vlan_ipv4_gw}}"
