---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: test
      debug: 
        msg: 
          - "src={{ vlan_src | default(omit) }}"
          - "vlan_num=={{ vlan_num | default(omit) }}"
          - "vlan_name={{ vlan_name | default(omit) }}"
          - "vlan_ipv4_sub={{ vlan_ipv4_sub | default(omit) }}"
          - "vlan_ipv4_gw={{ vlan_ipv4_gw | default(omit) }}"
