---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: debug var 
      debug: 
        msg: "src={{vlan_src}} \n
              vlan_num=={{vlan_num}} \n
              vlan_name={{vlan_name}} \n
              vlan_ipv4_sub={{vlan_ipv4_sub}} \n
              vlan_ipv4_gw={{vlan_ipv4_gw}} \n
              " 